In [1]:
import numpy as np

In [7]:
x = np.array([[1,2],[7,5]])

In [8]:
x.size # returns number of elements

4

In [9]:
x.shape # returns order of array

(2, 2)

In [10]:
x.ndim # returns dimension

2

In [11]:
x.dtype # returns data-type

dtype('int32')

In [12]:
x.nbytes # return bytes consumed

16

In [13]:
arr = np.array([1,3,5,3,9,7,6,8,11,16]) # Slicing

In [14]:
arr[1:]

array([ 3,  5,  3,  9,  7,  6,  8, 11, 16])

In [15]:
arr[:]

array([ 1,  3,  5,  3,  9,  7,  6,  8, 11, 16])

In [16]:
arr[3:7]

array([3, 9, 7, 6])

In [17]:
arr[-1]

16

In [18]:
arr[-2]

11

In [20]:
arr[:-1]

array([ 1,  3,  5,  3,  9,  7,  6,  8, 11])

In [30]:
np.log10(arr) #Logarithmic function 

array([0.        , 0.47712125, 0.69897   , 0.47712125, 0.95424251,
       0.84509804, 0.77815125, 0.90308999, 1.04139269, 1.20411998])

In [29]:
np.log10(x) 

array([[0.        , 0.30103   ],
       [0.84509804, 0.69897   ]])

In [25]:
np.sqrt(arr) #Square root

array([1.        , 1.73205081, 2.23606798, 1.73205081, 3.        ,
       2.64575131, 2.44948974, 2.82842712, 3.31662479, 4.        ])

In [27]:
np.std(arr) #Standard deviation

4.182104733265296

In [40]:
np.std(x) 

2.384848003542364

In [46]:
matrix1 = np.matrix([[2,4,8],[6,7,4]])
matrix2 = np.matrix([[3,1,9],[6,6,7]])

In [47]:
np.add(matrix1,matrix2) # Matrix Addition

matrix([[ 5,  5, 17],
        [12, 13, 11]])

In [50]:
np.ndim(matrix1)

2

In [53]:
np.subtract(matrix2,matrix1) # Matrix subtraction

matrix([[ 1, -3,  1],
        [ 0, -1,  3]])

In [56]:
np.divide(matrix1,matrix2) # Matrix division

matrix([[0.66666667, 4.        , 0.88888889],
        [1.        , 1.16666667, 0.57142857]])

In [78]:
y =np.array([[1,2],[4,6]])

In [79]:
np.concatenate((x,y),axis=0) # Concatenation

array([[1, 2],
       [7, 5],
       [1, 2],
       [4, 6]])

In [90]:
np.concatenate((x,y),axis=1)

array([[1, 2, 1, 2],
       [7, 5, 4, 6]])

In [82]:
np.stack((x,y),axis=1) # Stacking

array([[[1, 2],
        [1, 2]],

       [[7, 5],
        [4, 6]]])

In [83]:
a = np.array([1,2,5])

In [84]:
b = np.array([6,8,0])

In [146]:
np.stack((a,b))

array([[1, 2, 5],
       [6, 8, 0]])

In [124]:
matrix = np.array([[1,4,3,7],[5,7,8,6],[5,9,0,3]])

In [138]:
np.max(matrix) # max

9

In [139]:
np.min(matrix) # min

0

In [150]:
np.max((matrix),axis = 0) # max along columns

array([5, 9, 8, 7])

In [145]:
np.max((matrix),axis = 1) # max along rows

array([7, 8, 9])

In [159]:
matrix.reshape(12,1) # Reshape

array([[1],
       [4],
       [3],
       [7],
       [5],
       [7],
       [8],
       [6],
       [5],
       [9],
       [0],
       [3]])

In [162]:
matrix.T # Transpose of matrix

array([[1, 5, 5],
       [4, 7, 9],
       [3, 8, 0],
       [7, 6, 3]])

In [165]:
matrix.diagonal() # Diagonal of matrix

array([1, 7, 0])

In [191]:
vector_1 = np.array([1,2,3]) # Dot product of a vector
vector_2 = np.array([3,6,8])

In [192]:
np.dot(vector_1,vector_2)

39

In [209]:
mat1 =np.array([[1,3],[4,5]])
mat2 =np.array([[4,2],[4,6]])

In [210]:
mat1*mat2 # Element-wise multiplication

array([[ 4,  6],
       [16, 30]])

In [216]:
np.matmul(mat1,mat2) # Product of matrix

array([[16, 20],
       [36, 38]])

In [229]:
np.zeros([3,6]) # Generate matrix of zeros and ones

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [234]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [237]:
np.random.randint(1,9,4) # 4 Random numbers between 1 and 9

array([5, 3, 6, 1])

In [238]:
np.random.normal(1.0,2.0,6) # 6 Random numbers whose mean is 1 and standard deviation is 2

array([-1.11633333,  2.46812102,  2.7412627 ,  0.29543407,  3.62585858,
        0.06771594])